project:
  type: website
  output-dir: docs

website:
  title: "2025 WFA R Coding Workshop"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - materials.qmd
    tools:
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/s-cunningham/2025_WFA_R_Workshop
          - text: Report a Bug
            href:  https://github.com/s-cunningham/2025_WFA_R_Workshop/issues

format:
  html:
    theme: journal
    css: styles.css
    toc: false

editor: visual

